name: livetex_flutter_example
description: "Demonstrates how to use the livetex_flutter plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  livetex_flutter:
    path: ../

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  lottie: ^3.1.2


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
